simple-icons/svglint

- bin/cli.js
- package-lock.json
- package.json
Updated the CLI script to allow for patterns in the CLI, specifically on Windows (as it seems Unix was already working, based on [this](https://travis-ci.org/simple-icons/simple-icons/jobs/412377623) example). As you can see in the image below the CLI does not work with a pattern on my Windows 10 machine.
As suggested in #2, I used [glob](https://www.npmjs.com/package/glob) to achieve this.
> Use glob to allow for patterns in the CLI (on Windows)

- package-lock.json
- package.json
- src/rules/valid.js
- src/svglint.js
- test/valid.spec.js
In light of [this comment](https://github.com/simple-icons/simple-icons/pull/1112) I added XML validation to the linter. Since none of [the alternative parsers to htmlparser2](https://www.npmjs.com/package/htmlparser2#performance) seem to fail on the example given in [1], I decided to use [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) for this. I implemented as a "rule" that is always enabled through the default configuration.
- Don't implement it as a rule but as something that is more core to the functionality. Certainly possible, but I felt that utilizing the existing functionality for rules was more appropriate.
- Don't enable the rule by default. Possible upon request, but I figured this would be useful to most people so it would be best to enable by default
-
The …
> Add "valid" rule that checks if the SVG is valid XML

- README.md
The link in [NPM package README](https://www.npmjs.com/package/svglint) is pointing to `https://www.npmjs.com/src/rules/`.
> Absolutify README link to prevent 404 in NPM package page

- LICENSE
- package.json
This is mostly done in an effort to standardize the license I use across my projects.
Changing licenses is always a tricky thing. All code (and releases) prior to this change will of course continue being available under CC0. To avoid licensing mistakes, this update will be published in the next major version.
> Change LICENSE to MIT

- src/lib/linting.js
- test/custom.spec.js
Closes #20 
If you throw an `Error` from a custom rule is not reported, failing silently. I have used the `error` state in the absence of an `exception` state, but I'm not that familiar with the implementation as to define a new state because I'm not sure of the implications.
> Fail throwing Error from custom rule

- package-lock.json
- package.json
This resolves two vulnerable dependencies, namely: css-what & lodash (if this is merged #26 is obsolete).
Alternatively cheerio could be bumped to `^1.0.0-rc.10`. This has the same effect w.r.t. dependencies but would make SVGLint incompatible with anything below that.
Note that this technically includes some breaking changes. For full details see [the cheerio release notes](https://github.com/cheeriojs/cheerio/releases). The relevant breaking changes for SVGLint:
- Stricter parsing of HTML (https://github.com/cheeriojs/cheerio/commit/04091a4f9f44dc5124b53718d74a2a1bf768594c)
- Selectors (due to upgrade to [css-select `^4.0.0`](https://github.com/fb55/css-select/releases)):
- Several pseudo selectors are now stricter, in line with the HTML spec.
- Some attributes are now case-insensitive …
> Upgrade cheerio to `^1.0.0-rc.6`

- bin/cli.js
This pull only changes the output displayed in CLI for errors catched reading configuration files, for easier debugging.
```
> svglint icons/*.svg --ci
--------------------------- Log ---------------------------
(x) Failed to parse config: Unexpected token ':'
------------------------- Summary -------------------------
- No files linted
```
```
> svglint icons/*.svg --ci
--------------------------------------- Log ---------------------------------------
(x) Failed to parse config:
/.../simple-icons/scripts/utils.js:45
(_, ref) => {quot: '"', amp: '&', lt: '<', gt: '>'}[ref]
^
SyntaxError: Unexpected token ':'
at wrapSafe (internal/modules/cjs/loader.js:988:16)
at Module._compile (internal/modules/cjs/loader.js:1036:27)
at Object.Module._extensions..js …
```
> Show error tracebacks reading config files in CLI

- src/rules/examples/async.js
- src/rules/examples/elms.js
- src/rules/examples/identity.js
- src/rules/examples/throws.js
I'm getting the next error trying to run the examples:
```
bin/cli.js --config src/rules/examples/elms.js
(x) Failed to parse config: Error: Cannot find module '../lib/logger'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
at Function.Module._load (internal/modules/cjs/loader.js:529:25)
at Module.require (internal/modules/cjs/loader.js:657:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/home/mondeja/files/code/svglint/src/rules/examples/elms.js:1:78)
at Module._compile (internal/modules/cjs/loader.js:721:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
at Module.load (internal/modules/cjs/loader.js:620:32)
at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
at Function.Module._load …
```
> Fix require path error in examples

- src/lib/linting.js
- src/rules/custom.js
- test/custom.spec.js
> pass file info to rules

- src/rules/attr.js
- test/attr.spec.js
Closes #46
~~This implementation checks ordering of first attributes. If the element found has more attributes than those passed in `rule::order` and the order of these attributes is correct, then the linter will pass without throwing errors.~~
> Add attr special rule to enforce attributes ordering

- package-lock.json
- package.json
<details>
<summary>The npm audit report at fd8023b33d7ad86424d1ac5e9cbbbf51858db23a:</summary>
```
$ git switch update-deps
Switched to branch 'update-deps'
$ npm audit --production
=== npm audit security report ===                        
found 0 vulnerabilities
in 134 scanned packages
```
</details>
<details>
<summary>Compared to the npm audit report at 5c9613b818b7104812fa4efb143724a7eb9f3e1c:</summary>
```sh
$ git switch master
Switched to branch 'master'
$ npm audit --production
=== npm audit security report ===                        
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ …
```
> Update (runtime) dependencies to fix npm audit warnings

- bin/cli.js
- package-lock.json
- package.json
- src/cli/components/linting.js
- src/cli/components/log.js
- src/cli/components/separator.js
- src/cli/components/summary.js
- src/cli/util.js
- src/lib/logger.js
- src/lib/reporter.js
- test/attr.spec.js
- test/custom.spec.js
- test/elm.spec.js
- test/valid.spec.js
By setting the environment variables:
- `NO_COLOR`
- `SVGLINT_NO_COLOR`
And all the checks done by [supports-color](https://github.com/chalk/supports-color), like [terminal is not a TTY](https://github.com/chalk/supports-color/blob/2a5846724b19ac94eb96b2842cf4b7751af0d8e4/index.js#L83), setting the [environment variable `TERM` to `dumb` value](https://github.com/chalk/supports-color/blob/2a5846724b19ac94eb96b2842cf4b7751af0d8e4/index.js#L89), passing [`--no-color` command line option](https://github.com/chalk/supports-color/blob/2a5846724b19ac94eb96b2842cf4b7751af0d8e4/index.js#L17)... These are all included in latest version of chalk (v5) by default. This version is only compatible with Node>=12.20, so it is in line with SVGLint support.
I've not included a check for `color` option in …
> Allow to disable color in output

- bin/cli.js
- src/cli/config.js
- src/lib/linting.js
- src/lib/parse.js
- src/svglint.js
- Change two instances where the default export is an object of properties and change them into _regular_ exports (following https://github.com/birjj/svglint/pull/41#issuecomment-991701695 and related comments).
- Update the import statement of [`cheerio`](https://cheerio.js.org/) following a deprecation warning on the default export.
> refactor: address default import

- .github/workflows/release.yml
- .github/workflows/test.yml
Bumping now due to warnings about deprecated support for Node.js v12-based Actions and Actions using `save-state` and `set-output`.
> chore(deps): bump actions/checkout from v2 to v3

- package-lock.json
By `npm audit fix`.
Note that this does not affect end-users. Even though `minimatch` is a transitive dependency of `svglint` (through [`glob`](https://github.com/birjj/svglint/blob/8353c59af9d66b19ef0a8e0f93f39e11eea659a4/package.json#L36)):
```shell
$ npm ls minimatch --omit dev  
svglint@1.0.5 .../svglint
└─┬ glob@7.1.2
└── minimatch@3.0.4
$ npm ls minimatch --omit dev  
svglint@1.0.5 .../svglint
└─┬ glob@7.1.2
└── minimatch@3.1.2
```
installing `svglint` fresh will use the latest version of `minimatch`. Existing users of `svglint` can upgrade to a "safe"[^1] version of `minimatch` whenever they want (e.g. by running  `npm audit fix` themselves).
[^1]: I didn't actually look at the vulnerability report for `minimatch`, so I'm not even sure depending on v3.0.4 is "unsafe".
> chore(deps): bump minimatch from 3.0.4 to 3.1.2

- src/rules/attr.js
- test/attr.spec.js
Fixes #74
Adds support for appending a `?` to the end of an attribute config entry to make it optional. Optional attributes will be checked if they exist, but if they are missing and `rule::whitelist` is set it will not fail validation.
I'll update docs once this looks good to a maintainer.
> feat: add optional attr support

- package-lock.json
- package.json
- src/rules/valid.js
Upgrade [`fast-xml-parser`](https://www.npmjs.com/package/fast-xml-parser) from v3 to v4 in order to address a (according to npm) high severity vulnerability, namely CVE-2023-34104. I did not evaluate the impact of the CVE on this project, but upgrading is easy enough and avoids any potential problems. Plus, staying on the latest available version is always good :)
> Address high severity issue by upgrading `fast-xml-parser`

- bin/cli.js
- src/cli/components/separator.js
- src/cli/config.js
- src/cli/util.js
- src/lib/linting.js
- src/lib/parse.js
- test/api.spec.js
- test/attr.spec.js
- test/cli.spec.js
- test/custom.spec.js
- test/elm.spec.js
- test/valid.spec.js
Closes #72 
---
Explicitly import `process` to avoid using undeclared globals.
> Explicitly import `process`

- README.md
- bin/cli.js
- test/cli.spec.js
Closes #81 - /cc @PaulRBerg
---
Extend the CLI to support providing an SVG on [`stdin`]. The CLI will only do this when provided with the `--stdin` flag, I choose this design as it was the only reliable way of switching between files and stdin I could find.
The stdin flow is based on the [`Readable` docs] and just calls the JS API's [`lintSource` function](https://github.com/birjj/svglint/blob/2d0f467728a4ac5e4fcdab6e897781f154751269/src/svglint.js#L137) on the entire input.
[`stdin`]: https://nodejs.org/api/process.html#processstdin
[`readable` docs]: https://nodejs.org/api/stream.html#readablereadsize
> Lint SVG from stdin

- .github/workflows/release.yml
- .github/workflows/test.yml
Update the CI to run tests on Node.js v20 (earliest and latest release), update the tests jobs for MacOS and Windows to use Node.js v20 (see also #41, which introduced the test matrix) - and update remaining CI jobs to use Node.js v20 as well.
> Use Node.js v20 in continuous integration

- package-lock.json
- package.json
- src/lib/reporter.js
- test/api.spec.js
- test/cli.spec.js
- test/reporter.spec.js
Fix https://github.com/birjj/svglint/issues/91
> feat: Add atomic values in API messages

- src/rules/custom.js
- src/svglint.js
Not exhaustive but definitely much better than the current typing.
So you can use:
```js
/** @type {import('svglint').Config} */
export default {
rules: {
...
```
> Improve types for `Config`

- .github/workflows/release.yml
- .github/workflows/test.yml
Upgrade `actions/checkout` and `actions/setup-node` from v3 to v4 primarily to benefit from their upgrades from Node.js v16 (deprecated) to Node.js v20
> Bump GitHub Actions dependencies

- bin/cli.js
- test/cli.spec.js
- test/projects/with-config-no-default-export/.svglintrc.js
> Raise error when no default export found in configuration file

- test/api.spec.js
- test/attr.spec.js
- test/custom.spec.js
- test/elm.spec.js
- test/helpers.js
- test/projects/cjs/bar/.svglintrc.js
- test/valid.spec.js
Fixes tests for rules refactoring them. Currently, if you force a failure in a rule test, an error message will be printed but the test will not fail because raising an exception in the `on('done')` callback of the `Linting` event emitter class is not caught by mocha.
This fix has reproduced a race condition when using the library from source code, which is explained in a TODO comment.
> chore: Fix tests (reproduces a race condition bug)

- .github/workflows/test.yml
- README.md
- bin/cli.js
- src/lib/linting.js
- test/api.spec.js
- test/cli.spec.js
- test/helpers.js
- test/reporter.spec.js
Fixes #103
BREAKING CHANGE: Users consuming the API must call now `Linting().lint()`.
> fix: Fix race condition when using the API

- .github/codeql-config.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/test.yml
Ignore broken file for CodeQL. See https://github.com/simple-icons/svglint/security/code-scanning/tools/CodeQL/status/configurations/automatic/c4476d61850e12a69f9b7e3bfc5486372eefda10dd14f27df5d189056a453063
> chore: ignore path for CodeQL

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/verify.yml
See https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
The OIDC publishing requires npm 11.5.1 or later. The Node.js 24.8.0 has a higher npm ([11.6.0](https://nodejs.org/en/blog/release/v24.8.0)) bundled.
> Bump actions & use Node.js 24

- src/rules/attr.js
- test/attr.spec.js
#127 didn't really fixed #126, this PR fixes #126
#127 only fixed the case described in #126 but didn't fixed the real problem. The confusion comes from thinking that `whitelist` is related with `order: [...]` when it's not the case. Quoting the documentation;
> - `"rule::whitelist"`: If enabled, extra attributes beyond of the ones defined in additional keys are not allowed on the element. The value must be a boolean.
> fix: custom attribute ordering when more than one bad found
